### ISSUE TITLE
Returns 403 even though config is correctly set

### ISSUE THREAD

**Issue by rob-mccann** [tomschlick/fuel-s3#1]
It's saying "The AWS Access Key Id you provided does not exist in our records" dispite the fact that the set_auth is being called with the correct items.

I'm running the following command:

``` php
S3::put_object_file($file['saved_to'].$file['saved_as'], 'mybucket', '',  S3::ACL_PUBLIC_READ);
```

**Comment by tomschlick** [comment]
Well the classes are directly from amazon's php source. I use this every day in a project I am working on so i know it works. My guess is either you have your secret key/access id mixed up or maybe it has to do with ssl on your server? Maybe a config is overwriting it? Try to dump the config variables and make sure everything is as it seems. There is not much I can do without that info.

**Comment by rob-mccann** [comment]
Hey,

So it looks like I wasn't calling it properly.

Needed to do 

```
$s3 = new S3();
$s3->put_object(.....);
```

:]

**Comment by tomschlick** [comment]
No biggie. Glad you got it worked out!
