### ISSUE TITLE
S3 XML response is not right.

### ISSUE THREAD

**Issue by watanabeyu** [tomschlick/fuel-s3#6]
Now S3 response is below.

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"&gt;
  &lt;Name&gt;quotes&lt;/Name&gt;
  &lt;Prefix&gt;N&lt;/Prefix&gt;
  &lt;Marker&gt;Ned&lt;/Marker&gt;
  &lt;MaxKeys&gt;40&lt;/MaxKeys&gt;
  &lt;IsTruncated&gt;false&lt;/IsTruncated&gt;
  &lt;Contents&gt;
    &lt;Key&gt;Nelson&lt;/Key&gt;
    &lt;LastModified&gt;2006-01-01T12:00:00.000Z&lt;/LastModified&gt;
    &lt;ETag&gt;&quot;828ef3fdfa96f00ad9f27c383fc9ac7f&quot;&lt;/ETag&gt;
    &lt;Size&gt;5&lt;/Size&gt;
    &lt;StorageClass&gt;STANDARD&lt;/StorageClass&gt;
    &lt;Owner&gt;
      &lt;ID&gt;bcaf161ca5fb16fd081034f&lt;/ID&gt;
      &lt;DisplayName&gt;webfile&lt;/DisplayName&gt;
     &lt;/Owner&gt;
  &lt;/Contents&gt;
  &lt;Contents&gt;
    &lt;Key&gt;Neo&lt;/Key&gt;
    &lt;LastModified&gt;2006-01-01T12:00:00.000Z&lt;/LastModified&gt;
    &lt;ETag&gt;&quot;828ef3fdfa96f00ad9f27c383fc9ac7f&quot;&lt;/ETag&gt;
    &lt;Size&gt;4&lt;/Size&gt;
    &lt;StorageClass&gt;STANDARD&lt;/StorageClass&gt;
     &lt;Owner&gt;
      &lt;ID&gt;bcaf1ffd86a5fb16fd081034f&lt;/ID&gt;
      &lt;DisplayName&gt;webfile&lt;/DisplayName&gt;
    &lt;/Owner&gt;
 &lt;/Contents&gt;
&lt;/ListBucketResult&gt;

Each Node beginning is uppercase.
So that S3::get_bucket() is not working right.

please fix

**Comment by tomschlick** [comment]
Not sure what you're saying the problem is.
